# Generated by Django 4.1.7 on 2023-05-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=60)),
                ('birthdate', models.DateField()),
                ('dni', models.CharField(max_length=255)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='schools.club')),
            ],
        ),
    ]
