# Generated by Django 4.1.7 on 2023-05-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_coach'),
        ('deportist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportist',
            old_name='registrationcode',
            new_name='code',
        ),
        migrations.AddField(
            model_name='deportist',
            name='club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.club'),
        ),
    ]
