# Generated by Django 4.1.7 on 2023-04-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
