# Generated by Django 4.1.7 on 2023-04-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
