# Generated by Django 4.1.7 on 2023-04-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_facility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=255)),
                ("phonenumber", models.CharField(max_length=60)),
            ],
        ),
    ]
